### ISSUE TITLE
Blacklist effectiveness

### ISSUE THREAD

**Issue by grahamperrin** [dsrini-open/history-delete#1]
I added the extension to Waterfox 56.2.8, blacklisted `google.com`, felt lucky at https://www.google.com/ … arrived at https://www.google.com/doodles/ and found Google Doodles in history. 

Do I misunderstand the blacklist?

**Comment by dsrini-open** [comment]
The blacklist history will be auto-deleted on any Window close - if the option is selected (by default selected) in Settings. I didn't want to remove the history on every tab close or prevent adding the page visited to history itself. 
Firefox doesn't seem to recognize the window close option when it is the last window. You can either trigger the deletion manually by "Remove Blacklist history" or by "Remove for google.com". Or if you close any second open window, extension will automatically clear the blacklisted ones. I am thinking of changing this to auto-clear history on window open, so when firefox opens it clears the previous history, as a hack to the current situation. Please verify, and let me know if the issue still persists.

**Comment by dsrini-open** [comment]
Auto-removal feature is provided with white-listed domains. 
Black-list also removes history but on window close. 
Please review and update / provide a feedback.
