### ISSUE TITLE
inconsistent/confusing Whitelist alarm clearing noticications : even when disabled

### ISSUE THREAD

**Issue by Jean-Ricky** [dsrini-open/history-delete#10]
nice design & look
but getting "Cleared alarm for removing history based on whitelist" notifications even when "Enable Whitelist" and "Enable Clearing Whitelist on Interval" options are OFF

**Comment by dsrini-open** [comment]
That's right. Everytime, when firefox starts, plugin syncs the options, and creates alarm if configured. (If alarm not configured, just runs once to clear any alarm previously configured). 

No issue with it, just can try to remove the redundant check.

**Comment by dsrini-open** [comment]
Updated, please verify!
