### ISSUE TITLE
Permanent "Remove All but white list"

### ISSUE THREAD

**Issue by maverick74** [dsrini-open/history-delete#2]
First of all: GREAT GUI!!! It's really nice, simple and intuitive! Congratulations!!!

As to my feature request: I think it would be cool if, instead of clearing just the black list on window close, it would execute the "Remove all but white list" and do it continuously/constantly.

By "constantly" i mean like it's done in History Zebra (https://addons.mozilla.org/en-US/firefox/addon/history-zebra/), where as soon as the entry is created it gets immediately deleted (i think this could also solve #1 ).

**Comment by dsrini-open** [comment]
Added the functionality with v2.0. Please review and let me know. Sorry for the delay. 
Assuming closed.
