### ISSUE TITLE
Notification disable/enable

### ISSUE THREAD

**Issue by tenleftfingers** [dsrini-open/history-delete#9]
Great plug in - thank you!

When I close a tab I get a notification. This is because my whitelist is small. Could there be an option to stop notifications? They block parts of the UI I need :)

**Comment by dsrini-open** [comment]
Thanks for the request. 
Will add it to future request #

**Comment by Jean-Ricky** [comment]
nice design & looking
but inconsistent/confusing "Cleared alarm for removing history based on whitelist" notifications : even when "Whitelist" (AND "Clearing Withelist on Interval") are DISABLED

**Comment by dsrini-open** [comment]
Updated, please verify!

**Comment by ghost** [comment]
Success! Thank you very much! 🎉🙏
